### ISSUE TITLE
Creating ResultNumber to show the number of result. 

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#435] opened 2020-09-04 10:26 UTC

**Comment by knirirr** [comment] 2020-09-25 10:28
Is this a duplicate of https://github.com/FAIRsharing/fairsharing.github.io/issues/405 ?
There's no description provided so I'm not certain. 
If it is a duplicate then it can be labelled as such and closed.

**Closed as completed** 2020-10-02 14:25 UTC
Labels: duplicate, medium
