### ISSUE TITLE
Better error message for 3rd-party authentication errors

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1164] opened 2021-07-21 11:26 UTC
To test the system, I've just attempted to create a new user account in the rebuild via ORCID authentication. I wanted to see if it would let me when I already had a user account (with a different email address) that had the same ORCID **but was a standard FAIRsharing account and not authorized via ORCID**.

This is the error message I received, and I don't understand it :-) :
![orcid-auth](https://user-images.githubusercontent.com/143586/126481314-e83f8217-8497-4dea-a16b-d42199723ff9.png)
Does this mean that the system caught that an ORCID was present in a different FAIRsharing user account already, or that I have some setting on the ORCID site that is wrong?

So, part of this ticket is to help me understand the error, and the other part is to request any improvements in formatting that might be possible for the error messages like this please.

Thanks!

**Comment by knirirr** [comment] 2021-07-21 12:18
Duplicate of https://github.com/FAIRsharing/fairsharing.github.io/issues/889

**Comment by knirirr** [comment] 2021-07-21 12:39
This is the part of the message that is relevant to orcid:

![126481314-e83f8217-8497-4dea-a16b-d42199723ff9](https://user-images.githubusercontent.com/3583375/126489586-6f55b9ff-85ec-4e3c-b8cd-433eb4c1f8c7.png)

**Comment by allysonlister** [comment] 2021-07-21 12:47
Thanks @knirirr 

I do have two email addresses associated with my ORCID, a primary email address that doesn't match any user account in FAIRsharing, and a secondary email address that does match my main FAIRsharing user account. I have googled this error message with no luck. Do you have any idea why the system is throwing this error? I think it's worth investigating as we need to test these things before September...

**Comment by knirirr** [comment] 2021-07-21 13:45
The ORCID-related text in the previous comment is specific to our application. It means that ORCID doesn't want to tell us your email address because your account is configured to withhold this information.
The other parts of the error are because we can't create a user account without a valid email in the response from ORCID.

**Comment by allysonlister** [comment] 2021-07-21 16:07
OK thanks - I've sorted it at the orcid end :)

**Comment by knirirr** [comment] 2021-09-16 10:23
There is a discussion here (https://pyroeis.oerc.ox.ac.uk/#narrow/stream/8-FAIRsharing-Rebuild/topic/UI.20Feedback/near/32887) about only showing the provider_error if that's present (far easier said than done, of course).

**Closed as completed** 2022-06-14 13:03 UTC
Labels: duplicate
