### ISSUE TITLE
Green button with name disappears

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#2367] opened 2024-07-10 14:29 UTC
**Describe the bug**
"I am logged in, it does not appear in the upper right corner, the green button with my username, so it was not easy to understand in the beginning if I was logging in successfully or not! 
thanks for your work!" (Copied from email by M.P. Tomasino)

**To Reproduce**

**Expected behavior**
The green button needs to appear

**Screenshots**
<img width="953" alt="image" src="https://github.com/FAIRsharing/fairsharing.github.io/assets/39826987/707b23ba-a982-497b-a9e7-a22141caef13">

**Operating system and browser version**
 Microsoft Edge browser

**Additional context**

**Comment by knirirr** [comment] 2024-07-10 14:42
I just tried: Edge Version 124.0.2438.2, Fedora Atomic (Silverblue) 40, and could not reproduce the issue.

**Comment by knirirr** [comment] 2024-07-12 08:26
The user reports having Version 126.0.2592.87 (Official build) (64-bit). Is anyone able to try that out?

**Comment by knirirr** [comment] 2024-07-16 14:48
They now say: "I have just noticed this issue with Microsoft Edge.. however,  I am using chrome now and I have no problem"

**Comment by knirirr** [comment] 2024-07-16 15:12
As I am unable to reproduce this, don't have any further corroboration, and the user can use Chrome, I'll close it.

**Closed as completed** 2024-07-17 10:42 UTC
Labels: bug, wontfix
